#!/bin/bash
runner=$USER

install (){
pkill zsh
sudo su
cp daemon.conf /etc/pulse/daemon.conf
cp Monokai-Flat.colorscheme /home/$runner/.local/share/konsole/Monokai-Flat.colorscheme
cp zshrc /home/$runner/.zshrc
exit
}


echo "This will install an updated /etc/pulse/daemon.conf, ~/.zshrc, and a new Konsole theme."
echo "\nIt will also kill any open zsh instances, so please close those if they exist."
echo "Do you wish to continue?"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) install ; break;;
        No ) exit;;
    esac
done    
